vIOS-L2-01:
  hostname: 192.168.1.10
  username: admin
  password: admin123
  platform: cisco_ios
  
R1:
  hostname: 192.168.1.1
  username: admin
  password: admin123
  platform: cisco_ios

  
vIOS-L2-02:
  hostname: 192.168.2.10
  username: admin
  password: admin123
  platform: cisco_ios



